#!/bin/bash

echo go generate ./...
time go generate ./...
printf "\n"

time go "$@"
echo go "$@"
printf "\n"

echo git restore ./cmd/gophercises-quizgame/.version.txt
time git restore ./cmd/gophercises-quizgame/.version.txt
printf "\n"
