#!/bin/bash

declare go_cmd="${1:-not_set}"
shift 1

if [[ ! ${go_cmd} =~ ^(run|build)$ ]]; then
	printf "Usage: %s (run|build) args\n" "$0"
	exit 1
fi

declare ldflags_str=""
declare version
declare git_hash
declare git_version
declare build_time

version="$(git describe --tags 2> /dev/null || echo 0.0.0)"
git_hash="$(git rev-parse HEAD)"
git_version="$(git describe --tags --long)"
build_time="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

ldflags_str+="-X main.version=${version} "
ldflags_str+="-X main.gitVersion=${git_version} "
ldflags_str+="-X main.gitHash=${git_hash} "
ldflags_str+="-X main.buildTime=${build_time} "

echo go "${go_cmd}" -ldflags "${ldflags_str}" ./cmd/quiz/gophercises-quizgame.go --version
time go "${go_cmd}" -ldflags "${ldflags_str}" ./cmd/quiz/gophercises-quizgame.go --version
printf "\n"

echo go "${go_cmd}" -ldflags "${ldflags_str}" ./cmd/quiz/gophercises-quizgame.go "$@"
time go "${go_cmd}" -ldflags "${ldflags_str}" ./cmd/quiz/gophercises-quizgame.go "$@"
printf "\n"
