#!/bin/bash

declare -i retval=0
declare keep_ro=false
declare -a targets

mapfile -t targets < <(git grep --recursive --files-with-matches '^func main() {$' | xargs dirname)

for target in "${targets[@]}"; do
	if [[ ! -w . ]]; then
		chmod a+w .
		keep_ro=true
	fi

	printf "go generate: creating %s\n\n" "${PWD}/${target}/.version.txt"

	{
		git describe --tags --abbrev=0 || (( retval++ ))

		git describe --tags --long || (( retval++ ))

		git rev-parse HEAD || (( retval++ ))

		date -u '+%Y-%m-%dT%H:%M:%SZ' || (( retval++ ))

	} > "./${target}/.version.txt"

	cat "./${target}/.version.txt"

	printf "\n"

	if ${keep_ro}; then
		chmod a-w .
	fi
done

exit "${retval}"
