#!/bin/bash

declare -i retval=0
declare keep_ro=false

if [[ ! -w . ]]; then
	chmod a+w .
	keep_ro=true
fi

main()
{
	git describe --tags --abbrev=0 || (( retval++ ))

	git describe --tags --long || (( retval++ ))

	git rev-parse HEAD || (( retval++ ))

	date -u '+%Y-%m-%dT%H:%M:%SZ' || (( retval++ ))
}

printf "go generate: creating %s\n\n" "${PWD}/.version.txt"

main | tee ./.version.txt

printf "\n"

if ${keep_ro}; then
	chmod a-w .
fi

exit "${retval}"
