#!/bin/bash

declare -i retval=0

main()
{
	git describe --tags --abbrev=0 || (( retval++ ))

	git describe --tags --long || (( retval++ ))

	git rev-parse HEAD || (( retval++ ))

	date -u '+%Y-%m-%dT%H:%M:%SZ' || (( retval++ ))
}

main > .version.txt

exit "${retval}"
